---
- name: "Get the cert from {{ item.name }}"
  community.crypto.get_certificate:
    host: "{{ item.name }}"
    port: "{{ item.port }}"
  run_once: true
  register: cert

#- debug: msg={{cert.cert}}
#  tags:
#    - certs

- name: "Copy cert in tmp file"
  ansible.builtin.copy:
    content: "{{ cert.cert }}"
    dest: "/tmp/{{ item.filename }}.crt"
    mode: 0644

- name: Import freeipa certificate to the keystore
  community.general.java_cert:
    cert_path: "/tmp/{{ item.filename }}.crt"
    cert_alias: "{{ item.filename }}"
    keystore_path: "{{ java_home }}/lib/security/cacerts"
    keystore_pass: changeit
    keystore_create: true
    state: present
  notify:
    - "Restart keycloak"
